# Generated by Django 3.2.8 on 2021-10-23 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211023_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment_name',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 6, 9, 20, 239157, tzinfo=utc)),
        ),
    ]
